name: Deploy CloudFormation - S3 Bucket

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        required: true
        type: string
        description: bucket name
      bucket_acl:
        required: true
        type: string
        description: bucket acl
      port_context:
        required: true
        description: Details of the action and general port_context (blueprint, run id, etc...)
        type: string

jobs:
  deploy-cloudformation-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials ðŸ”’
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ inputs.bucket_name }}
          template: s3-bucket.yaml
          parameter-overrides: >-
            BucketName=${{ inputs.bucket_name }},
            BucketAcl=${{ inputs.bucket_acl }}

      - name: UPSERT S3 Bucket Entity in Port
        uses: port-labs/port-github-action@v1
        with:
          identifier: ${{ inputs.bucket_name }}
          title: ${{ inputs.bucket_name }}
          team: '[]'
          icon: S3
          blueprint: s3_bucket
          properties: |-
            {
              "bucket_name": "${{ inputs.bucket_name }}",
              "bucket_acl": "${{ inputs.bucket_acl }}"
            }
          relations: '{}'
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: UPSERT
          runId: ${{fromJson(inputs.port_context).runId}}